def loadFromDisk(self, calculation):
        """
        Read the spectra from the files generated by Quanty and store them
        as a list of spectum objects.
        """

        suffixes = {
            'Isotropic': 'iso',
            'Circular Dichroism (R-L)': 'cd',
            'Right Polarized (R)': 'r',
            'Left Polarized (L)': 'l',
            'Linear Dichroism (V-H)': 'ld',
            'Vertical Polarized (V)': 'v',
            'Horizontal Polarized (H)': 'h',
        }

        self.raw = list()
        for spectrumName in self.toPlot:
            suffix = suffixes[spectrumName]
            path = '{}_{}.spec'.format(calculation.baseName, suffix)

            try:
                data = np.loadtxt(path, skiprows=5)
            except (OSError, IOError) as e:
                raise e

            rows, columns = data.shape

            if calculation.experiment in ['XAS', 'XPS', 'XES']:

                xMin = calculation.xMin
                xMax = calculation.xMax
                xNPoints = calculation.xNPoints

                if calculation.experiment == 'XES':
                    x = np.linspace(xMin, xMax, xNPoints + 1)
                    x = x[::-1]
                    y = data[:, 2]
                    y = y / np.abs(y.max())
                else:
                    x = np.linspace(xMin, xMax, xNPoints + 1)
                    y = data[:, 2::2].flatten()

                spectrum = Spectrum1D(x, y)
                spectrum.name = spectrumName
                if len(suffix) > 2:
                    spectrum.shortName = suffix.title()
                else:
                    spectrum.shortName = suffix.upper()

                if calculation.experiment in ['XAS', ]:
                    spectrum.xLabel = 'Absorption Energy (eV)'
                elif calculation.experiment in ['XPS', ]:
                    spectrum.xLabel = 'Binding Energy (eV)'
                elif calculation.experiment in ['XES', ]:
                    spectrum.xLabel = 'Emission Energy (eV)'
                spectrum.yLabel = 'Intensity (a.u.)'

                self.broadenings = {'gaussian': (calculation.xGaussian, ), }
            else:
                xMin = calculation.xMin
                xMax = calculation.xMax
                xNPoints = calculation.xNPoints

                yMin = calculation.yMin
                yMax = calculation.yMax
                yNPoints = calculation.yNPoints

                x = np.linspace(xMin, xMax, xNPoints + 1)
                y = np.linspace(yMin, yMax, yNPoints + 1)
                z = data[:, 2::2]

                spectrum = Spectrum2D(x, y, z)
                spectrum.name = spectrumName
                if len(suffix) > 2:
                    spectrum.shortName = suffix.title()
                else:
                    spectrum.shortName = suffix.upper()

                spectrum.xLabel = 'Incident Energy (eV)'
                spectrum.yLabel = 'Energy Transfer (eV)'

                self.broadenings = {'gaussian': (calculation.xGaussian,
                                                 calculation.yGaussian), }

            self.raw.append(spectrum)

        # Process the spectra once they where read from disk.
        self.process()