def get_input(source, files, threads=4, readtype="1D",
              combine="simple", names=None, barcoded=False):
    """Get input and process accordingly.

    Data can be:
    - a uncompressed, bgzip, bzip2 or gzip compressed fastq file
    - a uncompressed, bgzip, bzip2 or gzip compressed fasta file
    - a rich fastq containing additional key=value information in the description,
      as produced by MinKNOW and albacore with the same compression options as above
    - a sorted bam file
    - a sorted cram file
    - a (compressed) sequencing_summary.txt file generated by albacore

    Handle is passed to the proper functions to get DataFrame with metrics
    Multiple files of the same type can be used to extract info from, which is done in parallel
    Arguments:
    - source: defines the input data type and the function that needs to be called
    - files: is a list of one or more files to operate on, from the type of <source>
    - threads: is the amount of workers which can be used
    - readtype: (only relevant for summary input) and specifies which columns have to be extracted
    - combine: is either 'simple' or 'track', with the difference that  with 'track' an additional
      field is created with the name of the dataset
    - names: if combine="track", the names to be used for the datasets. Needs to have same length as
      files, or None
    """
    proc_functions = {
        'fastq': ex.process_fastq_plain,
        'fasta': ex.process_fasta,
        'bam': ex.process_bam,
        'summary': ex.process_summary,
        'fastq_rich': ex.process_fastq_rich,
        'fastq_minimal': ex.process_fastq_minimal,
        'cram': ex.process_cram,
        'ubam': ex.process_ubam, }
    filethreads = min(len(files), threads)
    threadsleft = threads - filethreads
    with cfutures.ProcessPoolExecutor(max_workers=filethreads) as executor:
        extration_function = partial(proc_functions[source],
                                     threads=threadsleft,
                                     readtype=readtype,
                                     barcoded=barcoded)
        datadf = combine_dfs(
            dfs=[out for out in executor.map(extration_function, files)],
            names=names or files,
            method=combine)
    if "readIDs" in datadf and pd.isna(datadf["readIDs"]).any():
        datadf.drop("readIDs", axis='columns', inplace=True)
    datadf = calculate_start_time(datadf)
    logging.info("Nanoget: Gathered all metrics of {} reads".format(len(datadf)))
    if len(datadf) == 0:
        logging.critical("Nanoget: no reads retrieved.".format(len(datadf)))
        sys.exit("Fatal: No reads found in input.")
    else:
        return datadf