def declare_output_files():

    """
    This method establishes the output files from pycloudy grids
    For these simulations in which we are only want to calculate the emissivities from the hydrogen and helium lines
    most of the default files from pycloudy outputs are not required
    :return:
    """

    #Exclude these files from being generated by the simulations
    components_remove = [#['radius', '.rad'],
                         #['continuum', '.cont'],
                         #['physical conditions', '.phy'],
                         ['overview', '.ovr'],
                         ['heating', '.heat'],
                         ['cooling', '.cool'],
                         ['optical depth', '.opd']]
    for item in components_remove:
        pc.config.SAVE_LIST.remove(item)

    #Exclude these elements files from being generated by the simulations
    elements_remove = [#['hydrogen','.ele_H'],
                       #['helium','.ele_He'],
                       ['carbon', '.ele_C'],
                       ['nitrogen', '.ele_N'],
                       ['oxygen', '.ele_O'],
                       ['argon', '.ele_Ar'],
                       ['neon', '.ele_Ne'],
                       ['sulphur', '.ele_S'],
                       ['chlorin', '.ele_Cl'],
                       ['iron', '.ele_Fe'],
                       ['silicon', '.ele_Si']]
    for item in elements_remove:
        pc.config.SAVE_LIST_ELEMS.remove(item)

    return