def betas_for_events(self):
        """betas_for_events creates an internal self.betas_per_event_type array, of (nr_covariates x self.devonvolution_interval_size), 
        which holds the outcome betas per event type,in the order generated by self.covariates.keys()
        """
        self.betas_per_event_type = np.zeros((len(self.covariates), self.deconvolution_interval_size, self.resampled_signal.shape[0]))
        for i, covariate in enumerate(self.covariates.keys()):
            self.betas_per_event_type[i] = self.betas_for_cov(covariate)