def calc_derivation(passphrase, salt):
    """
    Calculate a 32 bytes key derivation with Argon2.
    :param passphrase: A string of any length specified by user.
    :param salt: 512 bits generated by Botan Random Number Generator.
    :return: a 32 bytes keys.
    """
    argonhash = argon2.low_level.hash_secret_raw((str.encode(passphrase)), salt=salt, hash_len=32,
                                                 time_cost=__argon2_timing_cost__, memory_cost=__argon2_memory_cost__,
                                                 parallelism=__argon2_parallelism__, type=argon2.low_level.Type.I)
    return argonhash